---
- hosts: '{{ hosts  }}'
  remote_user: root
  tasks:

      - name: Config Password Policy for CentOS 7
        shell: authconfig --enablereqlower --enablerequpper --enablereqdigit --enablereqother --passmaxclassrepeat=2 --passminlen=10 --passminclass=4 --passmaxrepeat=2 --update
        when: ansible_distribution == "CentOS" and ansible_distribution_major_version =='7'

      - name: Config Password Policy for CentOS 5 and CentOS 6 
        lineinfile: dest=/etc/pam.d/system-auth regexp="{{ item.regexp }}" insertbefore="{{ item.insertbefore }}" line="{{ item.line }}" state=present
        with_items:
          - { regexp: '^password    requisite     pam_cracklib.so try_first_pass retry=3 type=', insertbefore: '^password    sufficient' , line: 'password    requisite     pam_cracklib.so try_first_pass retry=3 type= minlen=10 dcredit=-1 ucredit=-1 lcredit=-1 ocredit=-1'}
        when: ansible_distribution == "CentOS" and ansible_distribution_major_version =='6' or ansible_distribution_major_version =='5'
